import http from 'node:http';
import { spawn } from 'node:child_process';
import { mkdtemp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createAgentReply, validateAgentReply } from './agent.mjs';

const ROOT=dirname(fileURLToPath(import.meta.url)),dataDir=await mkdtemp(join(tmpdir(),'libtv-agent-e2e-'));
const fakePort=3431,studioPort=3432,captures=[];let agnesCalls=0,repairFailCalls=0,cancelStarted=false,cancelClosed=false,timeoutClosed=false;
const plan={brief:{title:'雨夜归途',logline:'一个女孩在雨夜城市找到回家的方向。',audience:'短视频观众',platform:'抖音',aspectRatio:'9:16',targetDurationSec:18,tone:'克制温暖',ending:'晨光照亮她的脸'},styleBible:{visualStyle:'写实电影感',palette:'冷蓝到暖金',cameraLanguage:'稳定跟拍与近景',lighting:'雨夜霓虹和晨光',continuityRules:['女孩始终穿黄色雨衣','雨势逐镜减弱']},storyArc:['雨夜迷失','发现灯光','走向清晨'],shots:Array.from({length:3},(_,i)=>({title:`镜头 ${i+1}`,purpose:['建立迷失','出现希望','完成回归'][i],durationSec:6,composition:'人物位于画面下三分之一',action:'女孩沿湿漉街道前行',camera:'低机位缓慢跟拍',lighting:'蓝色霓虹侧光',imagePrompt:`黄色雨衣女孩，雨夜街道，镜头 ${i+1}`,videoPrompt:'女孩向前走，镜头稳定跟随，雨滴自然落下',audioNote:'雨声与轻微脚步声',continuityNote:'保持黄色雨衣和行进方向一致'}))};
const proposal=message=>({kind:'proposal',message,questions:[],plan});
const question={kind:'question',message:'先确认两个关键选择。',questions:['发布平台是什么？','目标时长是多少？'],plan:null};
const readJson=async req=>{const chunks=[];for await(const c of req)chunks.push(c);return chunks.length?JSON.parse(Buffer.concat(chunks)):{};};
const fake=http.createServer(async(req,res)=>{const body=await readJson(req);captures.push({url:req.url,headers:req.headers,body});res.setHeader('content-type','application/json');
  if(req.method==='GET'&&req.url==='/agnes/models')return res.end(JSON.stringify({object:'list',data:[{id:'fake-agnes'},{id:'fake-agnes-pro'},{id:'fake-agnes-image'}]}));
  if(req.url==='/openai/responses'){if(body.model==='timeout-model'){res.once('close',()=>timeoutClosed=true);return;}if(body.input?.includes('REFUSAL_TEST'))return res.end(JSON.stringify({output:[{content:[{type:'refusal',refusal:'fake refusal'}]}]}));if(body.input?.includes('RATE_LIMIT_TEST')){res.statusCode=429;return res.end(JSON.stringify({error:{message:'fake rate limit'}}));}return res.end(JSON.stringify({output:[{content:[{type:'output_text',text:JSON.stringify(question)}]}]}));}
  if(req.url==='/gemini/models/fake-gemini:generateContent')return res.end(JSON.stringify({candidates:[{content:{parts:[{text:JSON.stringify(proposal('这是第一版完整提案。'))}]}}]}));
  if(req.url==='/agnes/chat/completions'){const payload=JSON.stringify(body);if(payload.includes('CANCEL_TEST')){cancelStarted=true;res.once('close',()=>cancelClosed=true);return;}if(payload.includes('REPAIR_FAIL_TEST')){repairFailCalls++;return res.end(JSON.stringify({choices:[{message:{content:'still not json'}}]}));}if(payload.includes('CHUNK_BOUNDARY_TEST')){const output=JSON.stringify(proposal('等等')),split=output.indexOf('等等')+1;res.setHeader('content-type','text/event-stream');res.write(`data: ${JSON.stringify({choices:[{delta:{content:output.slice(0,split)}}]})}\n\n`);res.write(`data: ${JSON.stringify({choices:[{delta:{content:output.slice(split)}}]})}\n\n`);return res.end('data: [DONE]\n\n');}if(payload.includes('STREAM_TEST')){const output=JSON.stringify(proposal('这是 Agnes 的实时流式提案。'));res.setHeader('content-type','text/event-stream');for(let i=17;i<=output.length;i+=17)res.write(`data: ${JSON.stringify({choices:[{delta:{content:output.slice(0,i)}}]})}\n\n`);if(output.length%17)res.write(`data: ${JSON.stringify({choices:[{delta:{content:output}}]})}\n\n`);return res.end('data: [DONE]\n\n');}agnesCalls++;return res.end(JSON.stringify({choices:[{message:{content:agnesCalls===1?'not json':JSON.stringify(proposal('已按反馈调整镜头。'))}}]}));}
  res.statusCode=404;res.end(JSON.stringify({error:'not_found'}));
});
await new Promise(resolve=>fake.listen(fakePort,'127.0.0.1',resolve));
await mkdir(dataDir,{recursive:true});
const legacyProject={id:'legacy-project',name:'Legacy v1.3',settings:{},workflow:{version:2,nodes:[{id:'existing',type:'prompt',position:{x:10,y:20},data:{text:'keep me'}}],edges:[]},timeline:{fps:30,width:1280,height:720,items:[],tracks:{}},createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};
await writeFile(join(dataDir,'db.json'),JSON.stringify({version:1,projects:{[legacyProject.id]:legacyProject},jobs:{},assets:{}},null,2));
const child=spawn(process.execPath,['server.mjs'],{cwd:ROOT,env:{...process.env,PORT:String(studioPort),DATA_DIR:dataDir,OPENAI_API_KEY:'openai-test',OPENAI_BASE_URL:`http://127.0.0.1:${fakePort}/openai`,OPENAI_AGENT_MODEL:'fake-openai',GEMINI_API_KEY:'gemini-test',GEMINI_AGENT_BASE_URL:`http://127.0.0.1:${fakePort}/gemini`,GEMINI_AGENT_MODEL:'fake-gemini',AGNES_API_KEY:'agnes-test',AGNES_BASE_URL:`http://127.0.0.1:${fakePort}/agnes`,AGNES_AGENT_MODEL:'fake-agnes'},stdio:['ignore','pipe','pipe']});
let logs='';child.stdout.on('data',c=>logs+=c);child.stderr.on('data',c=>logs+=c);const base=`http://127.0.0.1:${studioPort}`,sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function request(path,options={},expected=200){const response=await fetch(base+path,options),body=await response.json();if(response.status!==expected)throw new Error(`${path}: expected ${expected}, got ${response.status}: ${JSON.stringify(body)}`);return body;}
async function send(providerId,modelId,content){return request(`/api/projects/${legacyProject.id}/agent/messages`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({providerId,modelId,content})},201);}
async function waitHealth(){for(let i=0;i<50;i++){try{if((await fetch(base+'/api/health')).ok)return}catch{}await sleep(100)}throw new Error(logs);}
try{
  const appSource=await readFile(join(ROOT,'public','app.js'),'utf8'),htmlSource=await readFile(join(ROOT,'public','index.html'),'utf8');if(!appSource.includes('async function readAgentStream')||!appSource.includes("accept:'application/x-ndjson'")||!appSource.includes("e.key==='Enter'&&!e.shiftKey&&!e.isComposing")||!appSource.includes('if(S.agentController)return')||!appSource.includes("type:'marquee'")||!appSource.includes('selectedNodeIds')||appSource.includes("message.role==='user'?'你':'Agent'")||htmlSource.includes('data-tool="select"')||htmlSource.includes('data-tool="connect"')||!htmlSource.includes('data-tool="pan"'))throw new Error('Agent streaming/message UI or canvas selection regression');
  let malicious=false;try{validateAgentReply({...proposal('x'),evil:true});}catch{malicious=true}if(!malicious)throw new Error('unsupported reply fields were accepted');
  for(const invalid of [{...question,questions:['1','2','3','4']},proposal('x')]){if(invalid.kind==='proposal')invalid.plan={...invalid.plan,shots:invalid.plan.shots.slice(0,2)};let rejected=false;try{validateAgentReply(invalid)}catch{rejected=true}if(!rejected)throw new Error('Agent reply limits were not enforced');}
  await waitHealth();let timedOut=false;try{await createAgentReply({project:{name:'Timeout',workflow:{nodes:[],edges:[]}},messages:[{role:'user',content:'timeout'}],models:[],providerId:'openai',modelId:'timeout-model',config:{openaiKey:'test',openaiBase:`http://127.0.0.1:${fakePort}/openai`,timeoutMs:50}})}catch(error){timedOut=error.name==='TimeoutError'}for(let i=0;i<20&&!timeoutClosed;i++)await sleep(25);if(!timedOut||!timeoutClosed)throw new Error('Agent provider timeout did not abort the upstream request');const models=(await request('/api/agent/models')).models;if(models.length!==4||!models.some(model=>model.modelId==='fake-agnes-pro')||models.some(model=>/image|video/i.test(model.modelId)))throw new Error(`Agnes text model discovery failed: ${models.map(model=>model.modelId)}`);
  const asked=await send('openai','fake-openai','做一个雨夜短片');if(asked.message.questions.length!==2||asked.proposal)throw new Error('question reply was not persisted');
  const first=await send('gemini','fake-gemini','9:16，18 秒');if(first.proposal?.status!=='pending')throw new Error('Gemini proposal missing');
  const revised=await send('agnes','fake-agnes','结尾再温暖一点');if(revised.proposal?.status!=='pending'||agnesCalls!==2)throw new Error('Agnes repair/proposal failed');let repeatedQuestion=false;try{await createAgentReply({project:{name:'Retry',workflow:{nodes:[],edges:[]}},messages:[{role:'assistant',content:'请说明产品。',questions:['产品是什么？']},{role:'user',content:'补水面霜'}],models:[],providerId:'openai',modelId:'fake-openai',config:{openaiKey:'test',openaiBase:`http://127.0.0.1:${fakePort}/openai`}})}catch(error){repeatedQuestion=String(error.message).includes('repeated questions')}if(!repeatedQuestion)throw new Error('Agent accepted repeated questions after a user answer');
  const session=await request(`/api/projects/${legacyProject.id}/agent`),old=session.proposals.find(item=>item.id===first.proposal.id);if(old.status!=='superseded')throw new Error('previous pending proposal was not superseded');
  await request(`/api/projects/${legacyProject.id}/agent/proposals/${old.id}/apply`,{method:'POST'},409);
  const jobsBefore=(await request(`/api/projects/${legacyProject.id}/generations`)).generations.length;
  const applied=await request(`/api/projects/${legacyProject.id}/agent/proposals/${revised.proposal.id}/apply`,{method:'POST'});if(applied.workflow.nodes.length!==7||applied.workflow.edges.length!==3)throw new Error('Agent graph shape is wrong');
  const secondApply=await request(`/api/projects/${legacyProject.id}/agent/proposals/${revised.proposal.id}/apply`,{method:'POST'});if(secondApply.workflow.nodes.length!==7)throw new Error('proposal apply is not idempotent');
  const created=applied.workflow.nodes.filter(node=>node.data?.agentProposalId===revised.proposal.id);if(created.length!==6||created.some(node=>['imageGen','videoGen'].includes(node.type)&&node.data.status!=='idle')||created.some(node=>node.type==='prompt'))throw new Error('Agent node metadata/status missing');
  if(applied.workflow.nodes.find(node=>node.id==='existing')?.data.text!=='keep me')throw new Error('existing workflow changed');
  const videoNodes=created.filter(node=>node.type==='videoGen');if(videoNodes.some(node=>node.data.forcedCapability!=='video.image_to_video'||!node.data.modelKey.startsWith('agnes::')))throw new Error('video defaults are not normalized to a real provider');
  const ids=new Set(applied.workflow.nodes.map(node=>node.id));if(ids.size!==applied.workflow.nodes.length)throw new Error('duplicate node ids');
  const agentEdges=applied.workflow.edges.filter(edge=>created.some(node=>node.id===edge.source));const edgeKeys=new Set(agentEdges.map(edge=>`${edge.source}:${edge.target}`)),positions=new Set(created.map(node=>`${node.position.x}:${node.position.y}`));if(edgeKeys.size!==agentEdges.length||positions.size!==created.length)throw new Error('Agent graph contains duplicate edges or positions');const bounds=node=>({x:node.position.x,y:node.position.y,w:['image','video'].includes(node.data.agentRole)?420:300,h:['image','video'].includes(node.data.agentRole)?640:220});for(let i=0;i<created.length;i++)for(let j=i+1;j<created.length;j++){const a=bounds(created[i]),b=bounds(created[j]);if(a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y)throw new Error(`Agent nodes overlap: ${created[i].data.agentRole}/${created[j].data.agentRole}`);}
  const jobsAfter=(await request(`/api/projects/${legacyProject.id}/generations`)).generations.length;if(jobsAfter!==jobsBefore)throw new Error('Agent triggered generation jobs');
  const persisted=JSON.parse(await readFile(join(dataDir,'db.json'),'utf8'));if(persisted.version!==2||persisted.projects[legacyProject.id].agentSession.messages.length!==6)throw new Error('v1 data migration/session persistence failed');
  const openai=captures.find(item=>item.url==='/openai/responses'),gemini=captures.find(item=>item.url.includes('/gemini/models/')),agnes=captures.find(item=>item.url==='/agnes/chat/completions');if(openai.body.text?.format?.type!=='json_schema'||openai.body.store!==false)throw new Error('OpenAI structured output contract missing');if(gemini.body.generationConfig?.responseMimeType!=='application/json'||gemini.body.generationConfig?.temperature!==0)throw new Error('Gemini structured output contract missing');if(agnes.body.response_format?.type!=='json_object'||agnes.body.temperature!==0||!agnes.body.messages?.[0]?.content.includes('"kind"'))throw new Error('Agnes JSON schema contract missing');
  const streamResponse=await fetch(`${base}/api/projects/${legacyProject.id}/agent/messages`,{method:'POST',headers:{'content-type':'application/json',accept:'application/x-ndjson'},body:JSON.stringify({providerId:'agnes',modelId:'fake-agnes-pro',content:'STREAM_TEST'})}),streamEvents=(await streamResponse.text()).trim().split(/\r?\n/).map(line=>JSON.parse(line));if(streamEvents.filter(event=>event.type==='delta').length<2||streamEvents.at(-1)?.type!=='final')throw new Error(`Agent real-time stream failed: ${JSON.stringify(streamEvents)}`);const boundaryResponse=await fetch(`${base}/api/projects/${legacyProject.id}/agent/messages`,{method:'POST',headers:{'content-type':'application/json',accept:'application/x-ndjson'},body:JSON.stringify({providerId:'agnes',modelId:'fake-agnes-pro',content:'CHUNK_BOUNDARY_TEST'})}),boundaryEvents=(await boundaryResponse.text()).trim().split(/\r?\n/).map(line=>JSON.parse(line));if(boundaryEvents.at(-1)?.message?.content!=='等等')throw new Error(`Agent stream corrupted repeated boundary text: ${JSON.stringify(boundaryEvents)}`);
  for(const content of ['RATE_LIMIT_TEST','REFUSAL_TEST'])await request(`/api/projects/${legacyProject.id}/agent/messages`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({providerId:'openai',modelId:'fake-openai',content})},502);
  await request(`/api/projects/${legacyProject.id}/agent/messages`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({providerId:'agnes',modelId:'fake-agnes',content:'REPAIR_FAIL_TEST'})},502);if(repairFailCalls!==2)throw new Error('Agent repair failure did not stop after one retry');
  const cancelController=new AbortController(),cancelRequest=fetch(`${base}/api/projects/${legacyProject.id}/agent/messages`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({providerId:'agnes',modelId:'fake-agnes',content:'CANCEL_TEST'}),signal:cancelController.signal});for(let i=0;i<40&&!cancelStarted;i++)await sleep(25);cancelController.abort();let canceled=false,cancelError='';try{await cancelRequest}catch(error){cancelError=error.name;canceled=error.name==='AbortError'}for(let i=0;i<40&&!cancelClosed;i++)await sleep(25);if(!cancelStarted||!canceled||!cancelClosed)throw new Error(`Agent cancellation did not reach the provider request (started=${cancelStarted}, client=${cancelError}, providerClosed=${cancelClosed})`);
  await request(`/api/projects/${legacyProject.id}/agent`,{method:'DELETE'});const cleared=await request(`/api/projects/${legacyProject.id}/agent`),workflow=await request(`/api/projects/${legacyProject.id}/workflow`);if(cleared.messages.length||workflow.nodes.length!==7)throw new Error('new conversation removed workflow or failed to clear session');
  console.log(JSON.stringify({ok:true,providers:['openai','gemini','agnes'],agnesModelsDiscovered:models.filter(model=>model.providerId==='agnes').length,streamedDeltas:streamEvents.filter(event=>event.type==='delta').length,repairAttempts:agnesCalls,question:true,proposalRevision:true,appliedNodes:created.length,idempotent:true,generationJobsCreated:0,migratedDbVersion:persisted.version},null,2));
}finally{child.kill('SIGTERM');fake.close();await Promise.race([new Promise(r=>child.once('exit',r)),sleep(1200)]);await rm(dataDir,{recursive:true,force:true});}
