function record(value) { return value && typeof value === 'object' && !Array.isArray(value) ? value : {}; }
function text(value) { return typeof value === 'string' && value.trim() ? value.trim() : undefined; }
function listText(value) { return Array.isArray(value) ? value.map(text).filter(Boolean) : []; }
function metaOf(node) { const root=record(node), data=record(root.data); return { ...root, ...data, ...record(data.creative) }; }

export function buildStandaloneCreativeContext({ project, workflow, timeline, assets, generations }) {
  const settings=record(project?.settings), creative=record(settings.creative), nodes=workflow?.nodes||[], edges=workflow?.edges||[], items=timeline?.items||[], projectAssets=assets||[], jobs=generations||[];
  const connected=new Set(); for(const edge of edges){const value=record(edge);if(text(value.source))connected.add(text(value.source));if(text(value.target))connected.add(text(value.target));}
  const scenes=new Set(listText(creative.scenes)), shots=new Set(listText(creative.shots)), characters=new Set(listText(creative.characters)), locations=new Set(listText(creative.locations)), styles=new Set(listText(creative.styles)), continuityGroups=new Set(listText(creative.continuityGroups));
  const incompleteNodeIds=[],failedNodeIds=[],unconnectedNodeIds=[],issues=[];
  for(const node of nodes){const root=record(node),id=text(root.id),meta=metaOf(node),type=text(root.type)||'unknown',status=(text(meta.status)||'idle').toLowerCase();for(const value of [meta.sceneId,meta.scene,meta.sceneName])if(text(value))scenes.add(text(value));for(const value of [meta.shotId,meta.shot,meta.shotName])if(text(value))shots.add(text(value));for(const value of [meta.characters,meta.characterIds])for(const item of listText(value))characters.add(item);for(const value of [meta.location,meta.locationId])if(text(value))locations.add(text(value));for(const value of [meta.style,meta.stylePreset])if(text(value))styles.add(text(value));if(text(meta.continuityGroup))continuityGroups.add(text(meta.continuityGroup));if(id&&nodes.length>1&&!connected.has(id))unconnectedNodeIds.push(id);if(id&&['queued','processing','running','pending'].includes(status))incompleteNodeIds.push(id);if(id&&['failed','error'].includes(status))failedNodeIds.push(id);if(id&&['imageGen','videoGen','textGen'].includes(type)&&!text(meta.prompt))issues.push({level:'warning',code:'missing-prompt',message:'生成节点缺少提示词',nodeIds:[id]});}
  const byKind={},assetIds=new Set(),referenceAssets=[];for(const asset of projectAssets){const value=record(asset),kind=text(value.kind)||'unknown';byKind[kind]=(byKind[kind]||0)+1;if(text(value.id))assetIds.add(text(value.id));const metadata=record(value.metadata);if(metadata.reference===true||metadata.isReference===true||text(metadata.role)==='reference')referenceAssets.push(text(value.id));}
  const missingAssetItemIds=[];let durationFrames=0;for(const item of items){const value=record(item),id=text(value.id),sourceAssetId=text(value.sourceAssetId);durationFrames=Math.max(durationFrames,Number(value.startFrame||0)+Number(value.durationInFrames||0));if(id&&sourceAssetId&&!assetIds.has(sourceAssetId))missingAssetItemIds.push(id);}
  if(unconnectedNodeIds.length)issues.push({level:'info',code:'unconnected-nodes',message:'画布存在未连接节点，可检查是否为素材或废弃节点',nodeIds:unconnectedNodeIds});if(failedNodeIds.length)issues.push({level:'blocker',code:'failed-generation',message:'存在失败的生成节点',nodeIds:failedNodeIds});if(missingAssetItemIds.length)issues.push({level:'blocker',code:'missing-timeline-assets',message:'Timeline 引用了不存在的素材',timelineItemIds:missingAssetItemIds});if(jobs.some(job=>['failed','error'].includes((text(record(job).status)||'').toLowerCase())))issues.push({level:'warning',code:'failed-generation-job',message:'最近生成任务中存在失败记录'});
  const blockers=issues.filter(issue=>issue.level==='blocker').length,warnings=issues.filter(issue=>issue.level==='warning').length;
  return {schemaVersion:1,mission:{name:text(project?.name)||'未命名项目',...creative},bible:{characters:[...characters],locations:[...locations],styles:[...styles],continuityGroups:[...continuityGroups]},graph:{nodeCount:nodes.length,edgeCount:edges.length,scenes:[...scenes],shots:[...shots],unconnectedNodeIds,incompleteNodeIds,failedNodeIds},assets:{total:projectAssets.length,byKind,referenceCount:referenceAssets.length},timeline:{fps:Number(timeline?.fps||30),width:Number(timeline?.width||1920),height:Number(timeline?.height||1080),itemCount:items.length,durationFrames,missingAssetItemIds},readiness:{score:Math.max(0,Math.min(100,100-blockers*30-warnings*10-(incompleteNodeIds.length?5:0))),blockers,warnings},issues};
}
